language: python
python:
  - "3.5"
  - "3.6"
cache: pip
dist: xenial
before_install:
  - "pip install -U pip"
  - "python setup.py install"
install:
  - pip install -r requirements.txt
script:
  - pytest
