language: python
python:
  - "3.5"
  - "3.6"
cache: pip
dist: xenial
before_install:
  - sudo apt-get install gfortran gcc ipython ipython3 cython cython3 libblas libblas3 libblas-dev libblas3-dev liblapack3 liblapack-dev libatlas3-dev  
  - "pip install -U pip"
  - "pip install 'cython>=0.18' 'assimulo==2.8'"  
  - "python setup.py install"
install: 
  - pip install -r requirements.txt
script:
  - pytest
